model_name: convnextv2_large
pretrained: True
weight: null

data: /workspace/src/data/data400.yaml
img_size: 224
val_split: 0.1

batch_size: 32
epoch: 30
lr: 0.0001
gce_q: 0.6
resize_scale: 0.2

workers: 5
seed: 3407

use_cleanlab: True
cleanlab: /workspace/src/cleanlab/webfg400_cleanlab_indices.npy

mixup: False

distill: False

project: train_output
name: webfg400_teacher_convnextv2_large
logger: null

local_rank: -1
master_addr: localhost
master_port: '12355'