weights: /workspace/train_output/webinat5000_main_dinov2_large/best_model.pt
model_name: dinov2_large
batchsize: 256
data: /workspace/src/data/data5000.yaml
output_dir: /workspace/test_output/webinat5000_results