# -*- coding: utf-8 -*-
"""GFT_COCO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Oi4XUqsLJT6FTextlEyP03jO07bXyZ4
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from timm import create_model
from timm.models.vision_transformer import Block



# Keep the original model architecture unchanged
class HierarchicalAttention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        # Smoothing conv layer
        self.smooth = nn.Conv1d(1, 1, kernel_size=3, padding=1, bias=False)
        nn.init.ones_(self.smooth.weight)

        self.ema_alpha = 0.9
        self.register_buffer('ema_grad', None)

    def compute_gradient_attention(self, attn_scores, window_size):
        B, H, N, _ = attn_scores.shape

        # Compute mean attention across heads
        mean_attn = attn_scores.mean(dim=-1)  # [B, H, N]

        # Compute gradients using finite differences
        grad = torch.zeros_like(mean_attn)
        grad[:, :, 1:-1] = (mean_attn[:, :, 2:] - mean_attn[:, :, :-2]) / 2.0
        grad[:, :, 0] = mean_attn[:, :, 1] - mean_attn[:, :, 0]
        grad[:, :, -1] = mean_attn[:, :, -1] - mean_attn[:, :, -2]

        # Take absolute value and average across heads
        importance_scores = grad.abs().mean(dim=1)  # [B, N]

        # Apply spatial smoothing
        importance_scores = self.smooth(importance_scores.unsqueeze(1)).squeeze(1)

        # Normalize scores
        importance_scores = (importance_scores - importance_scores.mean(dim=-1, keepdim=True)) / \
                          (importance_scores.std(dim=-1, keepdim=True) + 1e-6)

        # Update EMA during training
        if self.training:
            if self.ema_grad is None or self.ema_grad.shape != importance_scores.shape:
                self.ema_grad = importance_scores.detach()
            else:
                self.ema_grad = self.ema_alpha * self.ema_grad + \
                               (1 - self.ema_alpha) * importance_scores.detach()
            importance_scores = 0.5 * (importance_scores + self.ema_grad)

        # Final softmax with temperature scaling
        importance_scores = F.softmax(importance_scores / 0.1, dim=-1)

        return importance_scores

    def forward(self, x, window_size):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn_raw = attn.clone()
        attn = attn.softmax(dim=-1)

        # Compute gradient-based importance
        window_importance = self.compute_gradient_attention(attn_raw, window_size)

        attn = self.attn_drop(attn)
        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x, window_importance

class GFT(nn.Module):
    def __init__(self, base_model='vit_base_patch16_224', num_classes=80, patch_size=16):
        super().__init__()
        self.base_model = create_model(base_model, pretrained=True)

        # Calculate exact number of patches
        self.num_patches = (224 // patch_size) ** 2  # This is 196 for 224/16
        self.patch_size = patch_size
        self.num_classes = num_classes

        # Hierarchical attention blocks
        self.hierarchical_blocks = nn.ModuleList([
            HierarchicalAttention(dim=768, num_heads=12)
            for _ in range(3)
        ])

        self.classifier = nn.Linear(768, num_classes)

        # Define progressive patch selection sizes
        self.selection_sizes = [
          int(self.num_patches * 0.75),  # Keep 75% patches
          int(self.num_patches * 0.5),   # Keep 50% patches
          int(self.num_patches * 0.25),  # Keep 25% patches
        ]

    def select_patches(self, tokens, importance, k):
        B = tokens.size(0)
        N = importance.size(1)

        # Ensure k is not larger than the available patches
        k = min(k, N)

        # Get top-k indices
        _, top_k_idx = torch.topk(importance, k, dim=1)
        batch_idx = torch.arange(B, device=tokens.device).unsqueeze(1).expand(-1, k)

        # Select the top-k patches
        return tokens[batch_idx, top_k_idx]

    def forward(self, x):
        # Initial patch embeddings
        x = self.base_model.patch_embed(x)
        cls_token = self.base_model.cls_token.expand(x.shape[0], -1, -1)
        x = torch.cat((cls_token, x), dim=1)
        x = self.base_model.pos_drop(x + self.base_model.pos_embed)

        # Apply base transformer blocks
        for blk in self.base_model.blocks[:8]:
            x = blk(x)

        patch_tokens = x[:, 1:]  # Remove CLS token
        current_tokens = patch_tokens

        # Hierarchical attention refinement
        for i, (attn_block, select_size) in enumerate(zip(self.hierarchical_blocks, self.selection_sizes)):
            # Apply attention and get importance scores
            tokens_attn, importance = attn_block(current_tokens, window_size=14)  # Use constant window size

            # Select patches based on gradient importance
            current_tokens = self.select_patches(tokens_attn, importance, select_size)

        # Final classification
        x = torch.cat((x[:, 0].unsqueeze(1), current_tokens), dim=1)
        x = x[:, 0]  # Use CLS token
        x = self.classifier(x)

        return x

